### ISSUE TITLE
Adicionar monitoramento com prometheus

### ISSUE THREAD

**Issue by diogommartins** [b2wdigital/async-worker#106]
Podemos adicionar [prometheus_client](https://github.com/prometheus/client_python) como dependência para expor uma rota HTTP ( /asyncworker/metrics ) com métricas relacionadas ao framework.

## Ideias para a implementação da API Python de métricas

- Teremos um registry único por aplicação asyncworker. Esse registry pode ser automaticamente colocado na `App` assim que ela é instanciada;
-  Temos que pensar em uma interface pra esse Registry. Algumas açoes possíveis:
    - Poder adicionar labels fixas (já com valor) a todas as métricas; `sef add_label(self, name: str, value: str)`
    - Poder definir um prefixo para todss as métricas; `def set_prefix(self, prefix: str)`
    - Poder definir um sufixo para todas as métricas; `def set_suffix(self, suffix: str)`
    Um exemplo de como um código desse poderia ficar:
    ```python
    @app.run_on_startup()
    async def startup(app: App):
        app.metrics_registry
              .add_label("task_id", os.getenv("TASK_ID"))
              .add_label("host", os.getenv("HOST_ADDRESS")).
              .....
    ```
- Pensarmos em quais ENVs serão possíveis de serem passadas para influenciar instanciação do Registry default
- Pensar em como podemos ter um registry default dentro da `App` e ao mesmo tempo podermos fazer isso:
    ```python
    from asyncworker.metrics import Counter

    c = Counter(...)
    c.inc()
    ```
    Ou seja, mesmo o Registry estando dentro da `App` não precisamos ter a instância da `App` sempre em mãos, afinal podemos ter código instrumentado e que nem faz parte da camada de código onde a `App` é usada. Pensa em um "Service" que nem sabe de onde os dados vieram, se foi de um request HTTP ou de uma mensagem na fila.

## Sugestão de possíveis métricas:
- Quantidade de mensagens processadas agrupadas por rota e por tipo
- Quantidade de consumers ativos
- Quantidade de conexões ativas
- Quantidade de vezes que um bucket encheu
- Quantidade de vezes que um handler levantou um exceção 
- Quantidade de eventos emitidos (o que seriam esses "eventos"?)

A implementação também deve permitir que os usuários do asyncworker adicionem novas métricas nessa rota.

**Comment by george-veras** [comment]
Opa @diogommartins , o Prometheus também recebe "push" de métricas. Na verdade é um "workaround" para ele pode trabalhar com aplicações workers-like.

Deixa eu acrescentar um link aqui na conversa pra deixar registrado:
[Pushing Metrics](https://prometheus.io/docs/instrumenting/pushing/)

Esse abaixo é pro caso específico de Python:
[Exporting to a Pushgateway](https://github.com/prometheus/client_python#exporting-to-a-pushgateway)

Obrigado por me convidar a contribuir!

**Comment by daltonmatos** [comment]
Esse é um caminho que temos que seguir mesmo, para dar a possibilidade de expor esses número que são tão importantes.

Podemos começar com o prometheus_client e depois vemos se faz sentido construir alguma infra-estrutura para que o próprio asyncworker também faça push de métricas.

**Comment by dmvieira** [comment]
Gostaria de ajudar nisso aqui. Vocês tem algum planejamento? Eu posso fazer uso do pushgateway para implementar?

**Comment by daltonmatos** [comment]
> Gostaria de ajudar nisso aqui. Vocês tem algum planejamento? Eu posso fazer uso do pushgateway para implementar?

Boa @dmvieira !! Obrigado pela disponibilidade.

Penso que deveríamos usar o prometheus_client, pois é a forma padrão de funcionamento do prometheus. Ter o push gateway faria com que tivéssemos que ter algo cíclico dentro do código para fazer esse push.

Como o asyncworker permite que um worker qualquer tenha um endpoint http será melhor usarmos o client comum, que vai export um endpoint e o prometheus vem buscar as métricas.

Vamos usar esse ticket para podermos discutir como essa funcionalidade será implementada.

Algumas preocupações que já tenho:

- A porta que será aberta será a mesma da app? Podemos mudar esse valor?
- O IP onde o `bind()` será feito, será o mesmo da app? Podemos mudar? Pensa eum uma app que é pública mas que você não quer expor suas métricas para a internet e sim apenas para seu prometheus interno, via rede interna.
Para essas duas podemos ter novas ENVVARs análogas às que temos para a porta (`ASYNCWORKER_HTTP_PORT`) e bind-ip (`ASYNCWORKER_HTTP_HOST`) de workers HTTP.
- Quais os tipos de métricas que vamos expor? Todas que o prometheus client expõe?
- Como será um código que usa essas métricas? Um possível exemplo:

```python
from asyncworker.metrics import Gauge

users_online_gauge = Gauge()

async def login(...):
   users_online_gauge.inc()
```

algo assim?

- Que outras "interfaces" podemos expor para o uso da métricas? Penso que um decorator pode ser útil para métricas de contagem de tempo, por exemplo.

Acho que o primeiro passo é enumerar quais são todos os tipos de métricas possíveis. Depois disso vamos vendo como podemos mapear essas métricas dentro de um worker do asyncworker.

**Comment by daltonmatos** [comment]
Essa é a função que podemos usar para export as métricas: https://github.com/prometheus/client_python/blob/master/prometheus_client/exposition.py#L69-L129

No nosos caso criaremos um handler que responde pelo path `/metrics` e que chama essa função. Essa função recebe um registry como parametro então podemos até escolher usar um registry nosso (que não é o registry padrão do prometheus_client) se quisermos.

Não vi nada no prometheus client que seja um endpoint http usando python assíncrono, por isso teremos que escrever nosso handler que chama essa função deles.

**Comment by dmvieira** [comment]
Podemos começar com um caso mais simples? Ele precisa ser assíncrono? A gente precisa se preocupar com acesso público/privado agora?

Dado que não temos nenhuma integração, o que acha de diminuir um pouco o escopo da issue e criar outras complementares?

**Comment by daltonmatos** [comment]
Concordo, podemos fazer esse endpoint no mesmo http server que os outros endpoints estão, na mesma porta também. Sem probmelas. Temos apenas que saber que:

- Não poderemos ter, em nenhuma API feita com asyncworker, um endpoint chamado `/metrics`. Afinal esse endpoint estará "ocupado" com esse e endpoint que adicionaremos automaticamente;
- Para APIs que são públicas temos que tomar cuidado com exposição de métricas que podem conter dados sensíveis, por exemplo: Usuários online, talvez um métrica que tem como tag o email da pessoa, etc.

Em relação a ser assíncrono penso que precisa ser assíncrono sim. Penso no asyncworker como um framework exclusivamente assíncrono.

**Comment by daltonmatos** [comment]
Talvez então nessa primeira implementação podemos ter penas uma ENV que define se o endpoint de métricas será adicionado ou não, faz sentido? Tipo um `ASYNCWORKER_HTTP_METRICS_ENABLED="true` e ele seria por default false. Assim continuamos retro compatíveis com códigos que não têm ciência dessa nova funcionalidade e que eventualmente possam estar usando o endpoint `/metrics` para outro fim.

**Comment by dmvieira** [comment]
O que acha de permitir o uso de hooks no asyncworkers? Isso poderia ser um hook implementado a parte... Deixaria o sistema habilitado a "plugins"

Tava pensando que poderia ter uma estrutura bem flexível com todas as possibilidades de hooks assim como vocês tinham sugerido antes. Sugiro os seguintes hooks:
- on_receive(messages)
- before_consume(messages, time_spent) # time_spent é o tempo do on_receive até o before_consume
- on_success(messages, time_spent) # time_spent é o tempo do before_consume até o sucesso
- on_failure(messages, time_spent, error) # time_spent é o tempo do before_consume até o erro

O que vocês acham?

**Comment by daltonmatos** [comment]
Oi @dmvieira, tudo bem?

Penso que antes de termos quaisquer hooks precisamos pensar nas métricas. Acredito que esses hooks precisam ser dependentes do objetos que representam cada uma das métricas.

Até onde percebi os clients de prometheus funcionam em torno de um "registry", que é onde estão todas as métricas e no final, no momento de fazer o "dump" desse registry, é quando aquele output que conhecemos (o response do `/metrics`) aparece.

Talvez os hooks que você sugeriu sejam os "building blocks" para o que queremos fazer mas ainda temos que descobrir "o que queremos". :smiley: 

Acho que o jeito mais simples é pegar uma métrica e tentar escrever um códgo que usa essa métrica. Penso que nesse caminho vamos perceber o que precisamos e vamos adaptando essa "interface" que ainda vamos criar.

Não acho que devemos descartar totalmente os hooks mas tenho a impressão que eles são mais uma interface interna, privada do que o que os devs vão efetivamente usar no dia a dia.

A princípio o Pometheus fornece apenas 4 tipos de métricas: https://prometheus.io/docs/concepts/metric_types/

Vou te falar que achei que o client do prometheus faria mais por nós. Parece que ele é apenas a representação final do dado. Por exemplo, se quisermos saber o tempo médio de todos os requests (tavlez separado por `path` ou `host`) acho que teremos que fazer essa conta manualmente e no final representar isso com uma das 4 métricas do Prometheus.

O que acha de tentarmos escrever um exemplo de ponta a ponta? Sugiro uma métrica simples, ainda sem usar labels nem nada.

- Uma API HTTP com um endpoint que expõe uma métrica: Tempo médio de request. Esse número seria a métida geral de todos os requests.

Fazendo isso vamos poder ver como o código fica no final e aí vamos adaptando o que acharmos que ficou complicado ou muito trabalhoso de fazer, por exemplo. E quando terminarmos esse código já teremos:

- A Implementação do endpoint que será o `/metrics`, que vai ter acesso a esse "registry" de métricas e vai fazer o "dump" no formato que o prometheus entende.
- Ter uma ideia bem mais clara de como o código de uma app com métricas será escrito;

E depois vamos evoluindo e incluindo novas métricas.

Topa rabiscar esse código?

**Comment by dmvieira** [comment]
Mas você acha que precisamos implementar tudo que o Prometheus tem? Será que o envio de métricas chave já não satisfazem a gente? E se o usuário quiser usar métricas no StatsD ou outro sistema de métricas? Você acha que o framework deve suportar isso tudo?

**Comment by dmvieira** [comment]
Podemos rabiscar sim!

**Comment by daltonmatos** [comment]
> Mas você acha que precisamos implementar tudo que o Prometheus tem? Será que o envio de métricas chave já não satisfazem a gente? E se o usuário quiser usar métricas no StatsD ou outro sistema de métricas? Você acha que o framework deve suportar isso tudo?

Então, essa é uma outra questão. Que também vamos perceber com o tempo. Penso que o ideal é nós criarmos nossa própria abstração das métricas, os objetos que representam as métricas. Talvez nos mesmo moldes que o prometheus fez (Count, Gauge, Histogram, etc). Podemos ter nossos próprios objetos. E aí depois podemos pensar em ter múltiplos "backends" de implementação.

Já vejo duas macro categorias desses backends.

- Backends que fazer push de métricas, como o statsd
- Backends que entregam métricas quando "alguém vem buscar", como o prometheus.

Penso que podemos começar pensando apenas no prometheus, que acredito ser o padrão hoje em dia e depois vamos tentando pensar em como expandir. O que acha?

**Comment by dmvieira** [comment]
Nós começamos aqui de acordo com nossas necessidades aproveitando tudo do asyncworker: https://github.com/olxbr/BarterDude ... Vê o que faz sentido que podemos juntar no asyncworker... O que for muito fora de escopo podemos manter lá

**Comment by daltonmatos** [comment]
Que legal, @dmvieira !!! Me dá um tempo para digerir o projeto e aí podemos ver se pegamos alguma ideia de lá. Só o fato de vocês já usarem prometheus lá já vai dar pra ver um exemplo de como fazer.

Vou tentar fazer um hello world depois! :tada:

**Comment by daltonmatos** [comment]
Oi @dmvieira,

Dei uma olhada no Barter, ainda não fiz um hello world mas já entendi um pouco sobre ele e já peguei uns insights. Percebi que uma parte importante do Barter são os Hooks. Insights que peguei lá, por exempo:

- Healthcheck baseado na taxa de erros. Isso é bem legal! Não sei se penso em colocar um healthcheck automatico no asyncworker. Penso que o healthcheck é mais responsabilidade de quem está escrevendo o código e o asyncoworker sendo um framework genérico estaria "invadindo" o espaço da aplicação se fizesse isso. Mas expor métricas de taxa de erro automaticamente acho que faz **muito** sentido.
- Possivelmente adicoinar labels nessa métrica de exceção contento o tipo da exceção. Isso pode ser útil também. Assim dá pra montar um dashboard com um gráfico separado por tipo de exceção.
- Uma outra questão é a possibilidade de (pré) colocar prefixos, sufixos e labels (já com valor) em todas as métricas. Isso também é muito legal e faz sentido pro asyncworker, como um framework. Vou postar aqui ainda a impressão que tive ontem quando rabisquei um código usando as classes do `prometheus_client`.

Em relação a ter que instanciar o Registry de métricas antes de começar a usar ainda estou com algumas dúvidas (quase folisóficas, :smile:) que é o seguinte:

Penso que seria **muito agradável** poder importar os objetos de métricas diretamente, algo nessa linha:

```python
from asyncworker.metrics import Counter

c = Counter("list_users_ops", "Help String")

async def list_users(...):
  c.int()
  ...
  ...
```

Penso que seria melhor do que:

```python

from asyncworker.metrics import MetricsRegistry

registry = MetricsRegistry()
c = registry.Counter()

async def list_users(...):
  c.int()
  ...
  ...
```

mas ao mesmo tempo algumas informações devem ser passadas para o `MetricsRegistry` como por exemplo:

- labels fixas, como por exemplo:
    - ID da task que gerou aquelas métricas;
    - IP do host;
    - etc.
- Prefixos e namespaces que serão adicionados a **todas** as métricas.

Se não temos a possibilidade de instanciar o Registry manualmente temos que poder passar essas informações de uma outra forma. Uma possibilidade seria via ENVVAR mas tenho minhas dúvidas se ter **apenas** essa opção é um bom caminho.

Uma possibilidade é guardar o Registry dentro da `asyncworker.App`, assim temos a possibilidade de alterar esse registry no [@app.run_on_startup()](https://b2wdigital.github.io/async-worker/userguide/asyncworker-app/hooks.html#app-run-on-startup). Assim podemos mexer à vontade e adicionar o que acharmos necessário: Labels, Prefixos, Sufixos e tudo mais.

Pra quem não quer mexer em nada, basta não fazer nada que um Registry será instanciado automaticamente. E quem não quiser implementar o `@app.run_on_startup()` mas ainda assim quer configurar o registry aí podemos ter a possibilidade de ter ENVs que controlam isso. Algo nessa linha: `ASYNCWORKER_METRICS_DEFAULT_PREFIX`, `ASYNCWORKER_METRICS_DEFAULT_SUFFIX` e etc.

Vou editar a descrição dessa issue com algumas ideias que podem ser uma boa direção para essa implementação.

**Comment by daltonmatos** [comment]
Em relação às classes de métricas do `prometheus_client`.

Um ponto muito bom é que as metricas dele já possuem alguns dos gerenciadores de contexto que eu queria ter. Principalmente para métricas que incrementam e decrementam em um mesmo momento, usar o gerenciador de contexto é perfeito. Então muito provavelmente vamos nos inspirar nos gerenciadores que essa APi já expõe para fazermos os nossos aqui.
Um ponto muito estranho foi a necessidade de passar, na construção da métrica, quais serão as labels.

Um exemplo de código que lança exception:

```python
from prometheus_client.metrics import Counter

c = Counter("metric_id","Metric Help", ["path", "method"])

c.inc(path="/")

```

Ou seja, declarar que tenho duas labels mas na hora de usar a métrica eu passo apenas uma das labels.

Outra forma que também é ilegal na visão do `prometheus_client`:

```python

from prometheus_client.metrics import Counter

c = Counter("metric_id", "Metric Help", ["path"])

c.inc(path="/", method="GET")
```

Ou seja, ele também não permite que eu use labels "adicionais" no momento de usar uma métrica.

O que você pensa sobre isso? Você que já usa código com exposição de métricas do prometheus, vê sentido em podermos usar "mais livremente" as labels de uma métrica qualquer?

Um teste que ainda não fiz foi observar o comportamento do Prometheus quando ele vê uma **mesma métrica**, ou seja, uma métrica com o mesmo nome (`metric_id`, por exemplo) mas com labels diferentes. Quero tentar descobrir se isso compromete de alguma forma os dashboards montados.
Afinal se monto um dashboard onde quero separar apenas pela label `path` não deveria fazer diferença se as métricas possuem ou não a label `method`. O problema "começa" quando faço distinção pela label `method`. Nesse caso algumas métricas não seriam consideradas, mas pensando nisso acho que a métrica pode adicionar o valor `None` em vez de omitir a label no momento do output, saca?

Dessa forma se tiverem métricas onde uma label específica não foi chamada o gráfico vai mostrar uma linha atrelada ao valor `None`. Nesse momento perceberemos que existem partes do código que não estão passando essa label no momento de interagir com a métrica em questão.

**Comment by daltonmatos** [comment]
Outro ponto importante (mas não sei conseguiremos chegar a algum lugar) é pensar na análise estática do código. Seria muito legal que um código como esse pudesse ser analisado pelo `mypy`:

```python

from asyncworker.metrics import Counter

c = Counter("metric_id", "Metric Help", labels=["path"])

c.inc(method="GET") 
```

Seria muito legal que o `mypy` pudesse perceber que esse código está potencialmente errado. Já que declaramos uma label chamada `path` mas estamos passando para a métrica uma label chamada `method`.

Se conseguirmos fazer isso até prefiro ter uma "burocracia a mais" e ser forçado a pré-declarar as labels e só poder usar a métrica se todas as labels estivrem sendo passadas. 

Se não conseguirmos fazer isso penso que prefiro deixar mais "livre" e com menos "run time exceptions".

O legal de conseguir fazer isso que disse aqui é poder pegar erros **em tempo de desenvolvimento**. Isso seria muito bom, mas se não der podemos pensar em deixar o uso das labels mais permissivo, podendo usar labels à vondate por exemplo (a mais ou a menos do que foi declarado na instanciação da métrica).

**Comment by daltonmatos** [comment]
Essa interface foi implementada no #201. Mais detalhes na Doc: https://b2wdigital.github.io/async-worker/userguide/metrics/index.html#handler-metrics
