### ISSUE TITLE
Por que português?

### ISSUE THREAD

**Issue by dmvieira** [b2wdigital/async-worker#145]
Oi gente, tudo bem? Tem algum motivo pro projeto ser em português? Digo isso porque até em hacktoberfest ou para contribuição da comunidade o inglês facilita

**Comment by daltonmatos** [comment]
Oi @dmvieira, tudo bem?

De uns tempos pra cá tenho dedicado todos os meus esforços a produzir conteúdo exclusivamente em Português, na intenção de podermos oferecer conteúdo de qualidade para o público Brasileiro.

A documentação do README está, na verdade, sendo migrada para o [sphinx](https://www.sphinx-doc.org/en/master/) e as configurações já estão multi-língua, ou seja, quando fazemos o build da doc já geramos `pt_BR` (língua principal) e `en_US`, casjo exista tradução preenchida.

Isso significa que podemos ter a documentação em inglês também, mas alguém precisa manter. Eu mantenho a documentação em portugês, você estaria disposto a manter a versão em inglês?

Abraços,

**Comment by dmvieira** [comment]
Claro! Sem problemas
