### ISSUE TITLE
Como contribuir?

### ISSUE THREAD

**Issue by dmvieira** [b2wdigital/async-worker#146]
Oi, tudo bem? Não vi um CONTRIBUTING.md e nem como instala o projeto normalmente... É só o pip install? Seria legal um CODE_OF_CONDUCT.md também... Eu posso sugerir umas mudanças no readme para inclusão dessas coisas?

**Comment by daltonmatos** [comment]
De fato está sem nada nesse sentido. Pra instalar local bastaria mesmo um simples `pipenv install --dev` na pasta do projeto, isso já instala o próprio projeto em modo desenvolvimento no virtualenv que será criado.

Fique à vontade para abrir PRs. Serão muito bem vindos!

**Comment by daltonmatos** [comment]
Feito no #153.
