### ISSUE TITLE
consumer e publisher automático

### ISSUE THREAD

**Issue by dmvieira** [b2wdigital/async-worker#147]
Tem alguma coisa que já publique automaticamente em outra fila caso a função decorada rode com sucesso?

**Comment by daltonmatos** [comment]
Oi @dmvieira,

Então, pronto não tem nada em relação a isso. Mas pensando em uma implementação genérica poderíamos pensar em algo como "sucess hooks" que podem ser funções registradas para rodar depois que um handler termina com sucesso.

Nesse caso quem estiver implementando o worker em questão faria a implemenação dessa função e registraria como "success hook" de alguns handlers. O que acha?

Se achcar que faz sentido podemos discutir e pensar em uma interface para esses hooks. Temos que pensar também qual seria a sintaxe de reigistro de uma série de hooks para um handler.

Uma questão relevante também é se o hook rodaria **antes** ou **depois** do ack.

**Comment by diogommartins** [comment]
@dmvieira 
Automático não tem mesmo não, mas tem isso aqui:

```python
from typing import List

from asyncworker import App
from asyncworker.connections import AMQPConnection
from asyncworker.options import RouteTypes
from asyncworker.rabbitmq import RabbitMQMessage

amqp_conn = AMQPConnection(hostname="127.0.0.1", username="guest", password="guest", prefetch_count=256)
app = App(connections=[amqp_conn])


@app.route(["OLXBR_CHAT_NEW_MESSAGE-rate-limiter"], type=RouteTypes.AMQP_RABBITMQ)
async def handler(messages: List[RabbitMQMessage]):
    await amqp_conn.put(
        data={"dogs": ["Xablau", "Xena"]},
        exchange="OLXBR_CHAT_ANOTHER_EXCHANGE",
        routing_key=""
    )

app.run()
```

Isso é o suficiente pra consumir de uma fila `OLXBR_CHAT_NEW_MESSAGE-rate-limiter` e publicar  o JSON `{"dogs": ["Xablau", "Xena"]}` na exchange `OLXBR_CHAT_ANOTHER_EXCHANGE`.

**Comment by dmvieira** [comment]
Não podia pegar o retorno da função decorada e mandar pra outra fila?

**Comment by dmvieira** [comment]
@daltonmatos podemos deixar o usuário escolher com algum parâmetro como vai ser o ack

**Comment by daltonmatos** [comment]
> Não podia pegar o retorno da função decorada e mandar pra outra fila?

Sim. Mas temos sempre que pensar no asyncworker como um framework genérico. Escolher usar o retorno de um handler para um propósito fixo tem seu preço. É uma escolha que temos que fazer, de fato.

A sugestão que fiz no início foi pensando em construir ferramental para que a funcionalidade que estamos buscando possa existir. Por isso uma implementação genérica de "after hooks" (success/fail) pode se encaixar melhor do que uma implementação específica usando o retorno.

Publicar em outra fila após a execução de um handler é uma das opções. Podemos por exemplo qurer também que, após o processamento de uma mensagens (ou um lote delas), façamos uma chamada HTTP a outro serviço.

Se escolhermos usar o retorno da função como indicador de publicação em outra fila não teremos como implementar essa funcionalidade da chamada HTTP, por exemplo. A não ser que junto com o retorno vá uma indicação "do que fazer". Algo nessa linha:

```python
async def handler(msgs: List[RabbitMQMessage]):
  ....
  return (msgs, asyncworker.PUBLUSH_TO_QUEUE)
```
Ou

```python
async def handler(msgs: List[RabbitMQMessage]):
  ....
  return (msgs, asyncworker.HTTP_REQUEST)

```

Mas aí nesse caso estamos adicionando cada vez mais lógicas específicas dentro do framework, afinal ele deverá saber fazer requisição HTTP, postar em outra fila e outras opções que podem surgir.

A implementação com hooks faz tudo isso ser possível (com um pouco mais de código sob a responsabilidade de quem está programando) sem nem o framework saber o que está acontecendo.

Penso que esse deve ser o pensamento quando estamos escrevendo um código que pode ser usado para múltiplos propósitos (inclusive propósitos que nem sabemos quais são) como é o caso do asyncworker.

**Comment by daltonmatos** [comment]
> @daltonmatos podemos deixar o usuário escolher com algum parâmetro como vai ser o ack

Não entendi. Em que sentido você quer dizer "como vai ser o ack"?

Hoje existem algumas opções relacionadas a ack no asyncworker. E têm relação com o sucesso ou falha do handler. Podemos escolher por exemplo se a mensagem é devolvida ou não pra fila quando o handler falha.

O padrão é sempre devolver pra fila pois pensamos que uma mensagem nunca pode ser perdida. É essa doc aqui: https://github.com/b2wdigital/async-worker#configura%C3%A7%C3%B5es-de-a%C3%A7%C3%A3o-padr%C3%A3o-em-caso-de-sucesso-e-exception

Tem a ver com o que você tinha perguntado?

**Comment by dmvieira** [comment]
Tentei propor algo mais ou menos assim:

```
@app.forward(["MY_OTHER_EXCHANGE"], type=RouteTypes.AMQP_RABBITMQ)
@app.route(["MY_QUEUE"], type=RouteTypes.AMQP_RABBITMQ)
async def handler(message):
    await message
```
iria enviar para a exchange depois do ack

```
@app.route(["MY_QUEUE"], type=RouteTypes.AMQP_RABBITMQ)
@app.forward(["MY_OTHER_EXCHANGE"], type=RouteTypes.AMQP_RABBITMQ)
async def handler(message):
    await message
```
iria enviar para a exchange antes do ack

**Comment by dmvieira** [comment]
Estou pensando aqui e parece algo muito específico mesmo... Acho que vale estar fora daqui...
