### ISSUE TITLE
Lançamento de versão com licença

### ISSUE THREAD

**Issue by gligneul** [b2wdigital/async-worker#148]
Olá! Estou interessado em usar o projeto de vocês, mas pra isso preciso que a licença esteja explícita no projeto. Vi que vocês colocaram a licença no master; vocês poderiam também lançar uma versão com o arquivo de licença?

**Comment by daltonmatos** [comment]
Oi @gligneul, tudo bem?

Fechamos uma nova versão, já com a licença no código. https://pypi.org/project/async-worker/0.11.2/
