### ISSUE TITLE
objeto com async __call__ não é suportado como callback

### ISSUE THREAD

**Issue by dmvieira** [b2wdigital/async-worker#155]
A validação `get_type_hints` não permite que eu passe um objeto com implementação de call. Exemplo:

```
class MinhaCallback:
    def __init__(self):
        self._message = "Hello"
    async def __call__(self):
        return web.Response(text=self._message)

callback = MinhaCallback()

@app.route(....)
callback
```

**Comment by daltonmatos** [comment]
Interessante. Você acha que essa implementação de um handler em forma de Classe seria mais específica para handlers HTTP ou seria válida para todos os outros?

Outro ponto: Talvez se formos implementar o suporte a "class based" handlers seja melhor termos uma interface bem definida para essa classe em vez dela ser apens um "callable".

Pra um handler HTTP poderíamos ter algo nessa linha:

```python


@app.route(...)
class UserResourceHandler(HTTPHandler):

  async def post(self, user: UserResource) -> Response:
     pass

  async def get(self, ...):
    pass
```

Com um método python para cada métod HTTP, por exemplo. Estou só viajando aqui. =D

E pra um RabbitMQ (ou outros) poderiamos ter um RabbitMQHandler como classe base e um método específico para ser o entrypoint. Tipo um `async def execute(...)`.


O que acha?


Na verdade o próprio `HTTPHandler` citado acima poderia ser uma classe com esse método `execute()` também, mas ele recebe request e dependendo do HTTP METHOD faz o "dispatch" para o método correto do objeto `UserResourceHandler`.

**Comment by daltonmatos** [comment]
Em relação ao `__call__` acha seria viável adicionar suporte a classes que possuem apenas isso para serem anotadas pelo `app.route()`? Ou acham melhor decorarmos o classe direto mesmo (nos moldes da postagem acima)?

Outra dúvida: Como chegou nesse caso de uso?

**Comment by dmvieira** [comment]
Fizemos uma classe pra HTTP e íamos servir com call... Por mim se permitir a uso de algo mais Genérico como callable já funciona

**Comment by daltonmatos** [comment]
Entendi. Nesse caso o que vocês estão fazendo é ter um objeto com contexto interno trabalhando como um handler, né?

Em vez de termos algo assim:

```python

ctx = Context()

@app.route(...)
async def get_users(...):
    val = ctx.get_value(...)
```

Que seria um handler usando um contexto global do módulo. Seria algo assim:

```python

class MyHandler:
  def __init__(self, ...):
    self.ctx = Context()

  async def __call__(self, ...):
    val = self.ctx.get_value(...)
```

É mais ou menos isso o cenário onde vocês estão?

Se sim, talvez uma implementação possível seria fazer o `@app.route()` checar a presença do `__call__` e se existir passa ele para o `get_type_hints()`, afinal ele é o handler.

Faz sentido?

**Comment by dmvieira** [comment]
É exatamente isso!

**Comment by daltonmatos** [comment]
> É exatamente isso!

Beleza. Vou ver se penso em algo e faço um esboço sobre isso.

Você acha que essa implementação de handler como um objeto callable conviveria em harmonia com uma implementação de "class based view" mais complexa,nos moldes do que postei aqui (https://github.com/b2wdigital/async-worker/issues/155#issuecomment-585851211)?  

Ou acha que uma substuiria a outra?

No seu caso, que hoje é um objeto callable. Seria vantajoso migrar para uma classre onde cada método http é um método da classe, por exemplo?

**Comment by dmvieira** [comment]
Eu acho que foge do padrão o https://github.com/b2wdigital/async-worker/issues/155#issuecomment-585851211 do que temos hoje e talvez seja mais custoso... Por mim continua decorando uma "callable" e deixando a decisão em quem tá implementando, mas se quiser pensar na outra também acho maneiro...

**Comment by daltonmatos** [comment]
É, de fato ficaria bem diferente. Acho que em um primeiro momento dar suporte ao `__call__` seria um bom caminho.

**Comment by daltonmatos** [comment]
Fiz um esboço do que poderia ser essa implementação. Tentei fazer do jeito mais simples possível:

```python

try:
  handler = f.__call__
except AttributeError:
  handler = f
```

Mas o problema disso é que uma corotina (um simples `async def handler()`) **também** possui o método `__call__` e isso fazia com que o registro do handler no `routes_registry` passasse e ser feito com o `f.__call__` e não mais com `f` sendo a chave do dicionário.

Penso que o mais correto, pelo menos por enquanto, é continuar usando o objeto decorado como chave do dicionário final.

Dá uma olha e me diga se isso ajuda vocês.

**Comment by daltonmatos** [comment]
Outro ponto, que percebi durante a implementação:

Esse código:

```python
class MinhaCallback:
    def __init__(self):
        self._message = "Hello"
    async def __call__(self):
        return web.Response(text=self._message)

callback = MinhaCallback()

@app.route(....)
callback
```

Dá erro de sintaxe. Vocês estão fazendo o registro do handler dessa forma aqui, né?

```python
app.route(...)(handler)
```

**Comment by dmvieira** [comment]
Sim, estamos criando um handler e chamando na mão

**Comment by daltonmatos** [comment]
Show. Depois dá uma olhada no PR #160, veja se isso é o que faz ser possível o que vocês estão tentando fazer.

Se for faço o merge e fecho uma versão nova.

Valeu!
