### ISSUE TITLE
Transformar Dict `options` em modelo Pydantic (Dividir @app.poute() em decorators específicos)

### ISSUE THREAD

**Issue by daltonmatos** [b2wdigital/async-worker#157]
# Tarefas

- [x] Atualizar **todos** os exemplos da documentação para usar o novo decorator. Tanto exemplos de handlers HTTP quando exemplos de outros handlers.
- [x] Criar o enum com os methodos HTTP (#182)

# Racional

Atualmente temos apenas um decorator para registrar todos os tipos de handlers. O Desafio disso é que precisamos dar suporte a muitos conjuntos de parametros diferentes, apenas porque reusamos o mesmo decorator.

No passado isso pareceu vantajoso mas olhando hoje vejo que podermos ter decorators mais específicos. Isso vai nos dar uma outra vantagem que é poder transformar o parametro `options`, que hoje é um dict não tipado, em um modelo pydantic que pode definir de forma mais clara quais são as opções de cada handler.

Algo nessa linha:

```python

app = App()

@app.amqp.route(["/", "/other"], options=AMQPRouteOptions())
async def process_payment_message(...)
   ...
   ...
```

E o modelo do `AMQPRouteOptions` poderia ser:

```python

class AMQPRouteOptions(BaseModel):
    bulk_size: int = 1024
    bulk_flush_interval: int = 60
    on_success: Actions = Actions.ACK
    on_exception: Actoins = Actions.REJECT
```

Penso que isso nos dará a oportunidade de ter o objeto de opções mais bem definido e não vamos mais ficar fazendo acesso de dict (`["bulk_size"]`) pelo código. Além do analisador estático poder trabalhar melhor pra nós, já que agora o modelo tem campos bem definidos.

E a assinatura do `app.amqp.route()` seria algo assim:

```python
def rabbitmq(queues: List[str], options: Optional[RabbitMQOptions]):
   ...
```

faríamos isso para rodos os tips de handlers. Por enquanto http e rabbitmq.

**Comment by gligneul** [comment]
Ficaria bem melhor mesmo.

**Comment by daltonmatos** [comment]
Em vez de usar o namespace `handlers`, penso que usar o tipo de handler como primeiro namespace seja mais útil. Dessa forma podemos "agrupar" as funções em cada namespace, ex:

- `@app.http.route(...)`
- `@app.http.middleware(...)`
- `@app.amqp.route(...)`
- `@app.amqp.middleware(...)`

e aqui podemos ter novos namespaces no futuro, como:

- `@app.kafka.route()`
- `@app.pubsub.route()`
- etc

O interessante disso é que permite termos internamente uma interface que represenha um namespace completamente. Nesse exemplo acima cada namespace teria que implementar os métodos `route()` e `middleware()`.

Alguns métodos podem ter suas assinaturas fixas (por exemplo o `middleware()`) e outros não, como por exempo o `route()` que potencialmente pode ser diferente para cada namespace.

Acho melhor do que fazer o inverso, ou seja, ter o `middleware` e `route` como primeiro namespace e o tipo de handler (`http`, `amqp`, etc) como segundo. Pois dessa forma para eu poder adicionar um novo tipo de backend teria que mexer em todos os namespaces existentes.

Tendo o tipo de backend como primeiro namespace as implementações ficarão isoladas, ou seja, um novo tipo de backend apenas adiciona uma nova implementação (completa ou não) da interface que vamos definir.

Ainda estou experimentando algumas formas dessa interface e vou postando aqui o que for descobrindo de interessante.

**Comment by daltonmatos** [comment]
@diogommartins
