### ISSUE TITLE
Lançamento de versão

### ISSUE THREAD

**Issue by gligneul** [b2wdigital/async-worker#187]
@daltonmatos, você poderia lançar uma nova versão com as últimas modificações?

**Comment by daltonmatos** [comment]
Posso sim. Vou lançar a `0.12.1`. Se você estiver usando `0.11.x` vale atenção especial pois a `0.12.x` atualiza o pydantic.

Apesar da versão `0.12.x` ser uma versão que sinaliza uma breaking change é apenas atualização de dependência, o que geralmente é mais suave de lidar.

Então vale uma validação antes de fechar a versão do seu projeto, blz?

**Comment by daltonmatos** [comment]
https://pypi.org/project/async-worker/0.12.1/

**Comment by gligneul** [comment]
Muito grato
