### ISSUE TITLE
Conexões são vazadas quando a fila não existe no RabbitMQ

### ISSUE THREAD

**Issue by etandel** [b2wdigital/async-worker#196]
O async-worker trata como um erro de conexão se a fila mapeada na rota não existir no RabbitMQ, mesmo que os dados de conexão (host, porta, usuário e senha) estejam corretos. Isso faz com que ele fique em loop tentando reconectar, mas ele não fecha a conexão que já tinha sido aberta. Com isso, ele acaba abrindo várias conexões simultâneas com o RabbitMQ, podendo causar starvation de sockets ou file descriptors dependendo das configurações do servidor.

Acho que como fix dá pra fazer duas coisas:
1) colocar um backoff exponencial de entativa de reconexão
2) sempre tentar fechar a conexão atual antes de reconectar.

Acho que isso é relativamente simples de implementar, só preciso de umas indicações de onde modificar.

**Comment by daltonmatos** [comment]
Que interessante!

Tenho uma preocupação em relação a fechar a conexão atual: Se estamos lendo de mais de uma fila e uma dessas filas foi acessada com sucesso, se fecharmos a conexão atual vamos causar um novo problema. Pois quando o código tentar dar `ack()` receberá um erro pois a conexão (channel) daquela delivery tag não existe mais.... Faz sentido?

Talvez possamos pensar em algo mais genérico pra corrigir isso, como por exemplo perceber que o erro se refere a uma fila que não existe e tratar isso da forma correta. O que acha?

**Comment by etandel** [comment]
Faz sentido. Acho que são três problemas então:

1) Fila não existente é identificado como erro de conexão: 
     - Fix: tratar esse erro especificamente.

2) Não faz backoff em erros de conexão
     - Fix: adicionar backoff exponencial na retentativa

3) Não tenta fechar conexão atual antes de conectar de novo
     - Fix: tentar fechar conexão atual na retentativa


Acho que são 3 problemas independentes então, que podem ser tratados em separado, faz sentido?

**Comment by daltonmatos** [comment]
Acho que faz sim e podem inclusive serem implementados de forma totalmente independente. Minha única preocupação é com o item 3. Se formos fechar mesmo a conexão antes temos que ter algumas certezas:

- Não existe nenhuma delivery tag "em nossas mãos", ou seja, não tem ninguem com mensagem unacked
- Garantir que o erro que nos faz tentar conectar novamente é realmente um erro de conexão. Aqui talvez faça sentido mudarmos a exception sendo tratada para ser algo específico de erro e conexão. Aí temos que ver no `aioamqp` quais são as exceptions que ele expõe e que podemos pegar.

O que acha?

**Comment by etandel** [comment]
Acho que garantindo que o erro de conexão é de fato de conexão, não tem muito o que fazer se tivermos uma delivery tag em mãos, já que não vai dar pra fazer nada com ela porque a conexão morreu.

**Comment by daltonmatos** [comment]
Justo! Faz sentido mesmo! Quando o erro de conexão acontece as mensagens correspondentes a essas delivery tags já podem até ter sido devolvidas ao broker e outro worker já pode estar processando. Acho que esse é o caminho.

Penso que esse tratamento deve ocorrer idealmente no easyqueue e ele é quem vai fazer re-raise (se for o caso) das exceptions que queremos expor. O que acha?

**Comment by daltonmatos** [comment]
Descobri um outro problema aqui. 

Todos os consumers declarados em um projeto asyncworker e que usam uma mesma conexão usam também um mesmo channel[1]. O problema disso é que sempre que acontece um problema no momento de ligar um novo consumer (`channel.basic_consume()`, por exemplo) o channel em questão é **fechado**. 

Isso significa que todas as mensagens unacked de **outros** consumers (que usam essa mesma conexão) são devolvidas para o broker. O que é muito ruim pois a inexistência de uma fila qualquer pode interferir em um consumer que não tem nenhuma relação com isso.

Um exemplo simples:

```python
@app.route(
    ["queue", "queue-2"], type=RouteTypes.AMQP_RABBITMQ, options={Options.BULK_SIZE: 512}
)
async def handler(messages: List[RabbitMQMessage]):
    ...
```

Esse handler recebe mensagens de duas filas: `queue` e `queue-2`. No momento do boot da app o consume (`channel.basic_consume()`) é chamado em série para cada uma dessas duas filas. Assim que o consume começa na primeira fila (`queue`) o rabbit já começa a entregar mensagens para o asyncworker. Na iteração seguinte do `for` que está ligando os consumers o channel é fechado pois a segunda fila não existe (`queue-2`) e isso faz todas as mensagens serem devolvidas.

O problema disso é que essas mensagens podem já ter sido processadas pelo handler (não sabemos o tamanho dos buckets nem o tempo de flush) e esse problema pode causar duplicidade no processamentos das mensagens.

Talvez um simples check se a fila existe antes de iniciar o consumer pode ajudar. Mas também não sei sei é eficiente pois no tempo entre o `if fila existe` e o `channel.basic_consume(<fila>)` e fila pode deixar de existir.

Talvez uma implementação melhor seja uma sincronização dentro do próprio asyncworker que só inicia a entrega de mensagens para os handlers após todos os consumers serem iniciados com sucesso. Os que falharam geramos logs e seguimos em frente. Isso remove o problema das mensagens processadas em duplicidadae, já que um eventual unack com a mensagem ainda nas mãos do asyncworker não traz problema.

Um outro teste que fiz foi remover a fila após a app já estar rodando. Nada acontece, os outros consumers ficam de boa. E quando a fila volta o consumer antigo continua a ler/escrever dessa fila.

Não validei esse fluxo de remover a fila quando a conexão toda é fechada. Imagino que se eu remover a fila e fechar a conexão, quando o app reconectar o consume da fila que foi apagada vai falhar e vai ficar por isso mesmo, ou seja, se a fila for criada posteriormente nada será escrito/lido dela. Farei essa validação.


[1] https://www.rabbitmq.com/channels.html

**Comment by daltonmatos** [comment]
> Um outro teste que fiz foi remover a fila após a app já estar rodando. Nada acontece, os outros consumers ficam de boa. E quando a fila volta o consumer antigo continua a ler/escrever dessa fila.

Me enganei aqui. Apenas a escrita continua. O handler que recebe mensagens dessa filla não volta a recebê-las quando a fila é recriada.

**Comment by daltonmatos** [comment]
> Farei essa validação.

De fato é o que acontece. É como se a app fosse bootada quando uma das filas não existe. Nesse momento surgem duas situações:

1. O Bug descrito aqui pelo @etandel, onde novas conexões são criadas a cada loop de tentativa de iniciar os consumers
2. Nem a fila que existe onsegue ser consumida, pois a cada loop o único channel usado é fechado e isso se repete indefinidamente.

Temos então um segundo problema que é a impossibilidade de um projeto asyncworker bootar quando alguma fila mencionada em algum handler não existe. Vou abrir uma outra issue sobre esse ponto 2 para podermos discutir melhor lá (https://github.com/b2wdigital/async-worker/issues/214).

**Comment by daltonmatos** [comment]
Abri o PR #217 que corrige o problema do leak. Mas ainda falta a questão do bakcoff, que acho que poderíamos abrir uma nova issue para discutir isso, inclusive já fazer a implementação expondo métricas sobre esse backoff. Hoje o backoff é linear e com intervalo de 1s.

A questão do erro no momento de consumir de uma fila está no #214.
