### ISSUE TITLE
Forma como a label `path` é usada, em handlers HTTP, causa criação de timeseries indesejadas

### ISSUE THREAD

**Issue by diogommartins** [b2wdigital/async-worker#262]
# Definição do problema
Algo comum no padrão de construção de aplicações RESTful é o acesso a recursos em paths com o formato "`entidade`/`id`".  
No asyncworker, poderíamos representar o ato de acessar um registro da entidade `person` da seguinte forma:

```python
@app.http.get(["/person/{_id}"])
@parse_path
async def get_person_by_id(_id: int):
    person = {"id": _id}
    return web.json_response(person)
```

Ao executarmos chamadas para `/person/1`, `/person/2`, `/person/3`, métricas são contabilizadas considerados como paths, `/person/1`, `/person/2` e `/person/3` ao invés de `/person/{_id}`. De cara, vejo alguns pontos negativos:

1. Isso faz com que N séries temporais possam ser criadas 
2. Abre a possibilidade para algum tipo de negação de serviço (ref. 1)
3. Dificuldade para visualização e agregação de métricas cujos recursos façam uso de uma poderosa feature suportada pelo async-worker (ref. 2)

# Sugestão

* Refatorar a forma como estamos emitindo métricas HTTP para considerar como `path` a rota definida pelo usuário na definição de rota. Isso pode ser feito usando o atributo `canonical` da rota. Através de um `request: web.Request`, pode ser acessado da seguinte forma: `request.match_info.route.resource.canonical`

# Referências

1. https://prometheus.io/docs/practices/naming/#labels - Aviso na documentação do prometheus sobre má prática na utilização de labels
2. https://b2wdigital.github.io/async-worker/userguide/handlers/http/doc.html#recebendo-parametros-vindos-do-path-do-request
3. https://docs.aiohttp.org/en/stable/web_reference.html?highlight=canonical#aiohttp.web.DynamicResource.canonical

**Comment by diogommartins** [comment]
![image](https://user-images.githubusercontent.com/6271498/114318867-4f169380-9ae5-11eb-88c1-a2889f33c04b.png)

**Comment by daltonmatos** [comment]
De fato esse é um caso onde não temos controle sobre a quantidade de valores distintos que essa label pode ter. Acho muito válido mudarmos a métrica para ser apenas o "full path" que foi definido lá no handler.  👍🏽 

A ideia por trás dessa label era mais no sentido de "e se eu quiser saber o tempo médio de uma request para um cliente X"? Mas de fato, saber isso direto na métrica não parece ser o lugar certo.

**Comment by daltonmatos** [comment]
A ideia é pegar o path exato que está no `@app.http.*(...)`? Como faremos com handlers que possuem multi-path na definição? Isso será um problema?

**Comment by diogommartins** [comment]
> De fato esse é um caso onde não temos controle sobre a quantidade de valores distintos que essa label pode ter. Acho muito válido mudarmos a métrica para ser apenas o "full path" que foi definido lá no handler. 👍🏽

Dei mole na hora de implementar e testar. Não pegamos esse comportamento do path nos testes porque não teve nenhum caso de teste com handler dinâmico :/

> A ideia por trás dessa label era mais no sentido de "e se eu quiser saber o tempo médio de uma request para um cliente X"? Mas de fato, saber isso direto na métrica não parece ser o lugar certo.

Nem da forma como está hoje é possível linkar uma métrica a um cliente. Concordo que não é papel das métricas.

**Comment by diogommartins** [comment]
> A ideia é pegar o path exato que está no `@app.http.*(...)`? Como faremos com handlers que possuem multi-path na definição? Isso será um problema?

Sem problemas, já que tiramos a informação do path definido no handler da própria request.


(Da primeira vez que tentei responder seu comentário, acabei editando o seu e escrevendo em baixo 🤦. Desculpa! )

**Comment by daltonmatos** [comment]
Achei que essa era uma breaking change, pois muda a forma como a métrica é exposta. Acha que vale voltar a label de breaking-change?
